import { IMachine } from '../interfaces/IMachine';

export const equipment: IMachine[] = [
    {
        _id: '1',
        name: 'Machine1',
        ipv4: '192.168.1.1',
        mac: '00:0a:95:9d:68:16',
        os: 'Windows 10',
        manufacturer: 'Dell',
        description: 'Dell laptop with Windows 10',
        status: 'Active',
    },
    {
        _id: '2',
        name: 'Machine2',
        ipv4: '192.168.1.2',
        mac: '00:0a:95:9d:68:17',
        os: 'macOS Big Sur',
        manufacturer: 'Apple',
        description: 'MacBook Pro with macOS Big Sur',
        status: 'Active',
    },
    {
        _id: '3',
        name: 'Machine3',
        ipv4: '192.168.1.3',
        mac: '00:0a:95:9d:68:18',
        os: 'Ubuntu 20.04',
        manufacturer: 'Lenovo',
        description: 'Lenovo desktop with Ubuntu 20.04',
        status: 'Inactive',
    },
    {
        _id: '4',
        name: 'Machine4',
        ipv4: '192.168.1.4',
        mac: '00:0a:95:9d:68:19',
        os: 'Windows 11',
        manufacturer: 'HP',
        description: 'HP laptop with Windows 11',
        status: 'Active',
    },
    {
        _id: '5',
        name: 'Machine5',
        ipv4: '192.168.1.5',
        mac: '00:0a:95:9d:68:20',
        os: 'macOS Monterey',
        manufacturer: 'Apple',
        description: 'iMac with macOS Monterey',
        status: 'Inactive',
    },
];